### Set-Up

In [1]:
#!conda install tflearn
#!conda install pip
#!pip install tflearn

In [1]:
import tensorflow as tf
import imp  # to reload modules 
import tflearn
import cv2 
import numpy as np
from matplotlib import pyplot as plt
import matplotlib

from PIL import Image
from IPython.display import display
import pandas as pd
import os 

# mongoDB
import pymongo
from pymongo import MongoClient


Instructions for updating:
non-resource variables are not supported in the long term


### Connect to MongoDB

In [2]:
# mongo client
client = MongoClient('mongodb+srv://dana7k:EHYxKq3uBxyZzPrP@engagement.pouvh.mongodb.net/engagement?retryWrites=true&w=majority')

In [3]:
# get database
db = client.engagement
db

Database(MongoClient(host=['engagement-shard-00-00.pouvh.mongodb.net:27017', 'engagement-shard-00-01.pouvh.mongodb.net:27017', 'engagement-shard-00-02.pouvh.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', authsource='admin', replicaset='atlas-14bkw3-shard-0', ssl=True), 'engagement')

In [4]:
# list existing collections
db.list_collection_names()

['pictures']

In [5]:
# get a handle to a collection
collection = db.pictures
collection

Collection(Database(MongoClient(host=['engagement-shard-00-00.pouvh.mongodb.net:27017', 'engagement-shard-00-01.pouvh.mongodb.net:27017', 'engagement-shard-00-02.pouvh.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', authsource='admin', replicaset='atlas-14bkw3-shard-0', ssl=True), 'engagement'), 'pictures')

In [6]:
# examine a single record
collection.find_one()

{'_id': ObjectId('5fb70e998c853742a18d86f8'),
 'user_id': 'test',
 'picture': 'example3.jpg',
 'behavior': 'off_task',
 'emotion': 'confused'}

In [7]:
collection.count_documents({})

487

In [206]:
# a helper method to query from mongoDB
def get_mongoDB_query_as_df(collection, query):
    cursor = collection.find(query)
    # Expand the cursor and construct the DataFrame
    df =  pd.DataFrame(list(cursor))
    df = df.drop_duplicates(subset=['picture'])
    return df

### Query MongoDB for Sample Data 

In [204]:
query = {"user_id": "casey"}
df_casey = get_mongoDB_query_as_df(collection, query)
df_casey

_id user_id         picture behavior  \
0    5fb72727faa9571442a5fee4   casey  example140.jpg  on_task   
1    5fb7273bfaa9571442a5fee5   casey   example37.jpg  on_task   
2    5fb7274529630080345884eb   casey  example183.jpg  on_task   
3    5fb7274dfaa9571442a5fee6   casey   example22.jpg  on_task   
4    5fb72758faa9571442a5fee7   casey   example86.jpg  on_task   
..                        ...     ...             ...      ...   
196  5fbb200be2169171933e9e72   casey  example165.jpg  on_task   
197  5fbb2010e2169171933e9e73   casey  example162.jpg  on_task   
198  5fbb2014e2169171933e9e74   casey   example28.jpg  on_task   
199  5fbb201bbe96d4c429bfea42   casey   example70.jpg  on_task   
200  5fbb204ebe96d4c429bfea43   casey   example36.jpg  on_task   

                   emotion  
0    cant_decide_emotional  
1    cant_decide_emotional  
2                satisfied  
3                satisfied  
4                satisfied  
..                     ...  
196              satisfied  
197                  bored  
198              satisfied  
199               confused  
200              satisfied  

[201 rows x 5 columns]

In [105]:
query = {"user_id": "alexandra"}
df_alexandra = get_mongoDB_query_as_df(collection, query)
df_alexandra

_id    user_id         picture  behavior  \
0    5fb83c8651736e2ea19cfdb8  alexandra  example149.jpg  off_task   
1    5fb83c9376b1880504ea6e01  alexandra  example188.jpg   on_task   
2    5fb83c9c51736e2ea19cfdb9  alexandra   example44.jpg  off_task   
3    5fb83ca376b1880504ea6e02  alexandra   example23.jpg   on_task   
4    5fb83cad51736e2ea19cfdba  alexandra   example52.jpg   on_task   
..                        ...        ...             ...       ...   
196  5fb843c376b1880504ea6e61  alexandra   example60.jpg  off_task   
197  5fb843cd51736e2ea19cfe1c  alexandra   example93.jpg  off_task   
198  5fb843d576b1880504ea6e62  alexandra  example118.jpg  off_task   
199  5fb843dc76b1880504ea6e63  alexandra  example130.jpg   on_task   
200  5fb843e176b1880504ea6e64  alexandra  example161.jpg  off_task   

                   emotion  
0                 confused  
1                 confused  
2                    bored  
3                satisfied  
4                satisfied  
..                     ...  
196  cant_decide_emotional  
197  cant_decide_emotional  
198              satisfied  
199               confused  
200                  bored  

[201 rows x 5 columns]

In [107]:
df_alexandra[df_alexandra.picture == "example140.jpg"]

_id    user_id         picture  behavior emotion
136  5fb8413951736e2ea19cfdf8  alexandra  example140.jpg  off_task   bored

In [205]:
df_casey[df_casey.picture == "example140.jpg"]

_id user_id         picture  behavior  \
0   5fb72727faa9571442a5fee4   casey  example140.jpg   on_task   
62  5fbb1c8ebe96d4c429bfe9ff   casey  example140.jpg  off_task   

                  emotion  
0   cant_decide_emotional  
62               confused

In [111]:
result = pd.merge(df_casey, df_alexandra, on = 'picture', how='outer')
result

_id_x user_id_x         picture behavior_x  \
0    5fb72727faa9571442a5fee4     casey  example140.jpg    on_task   
1    5fb7273bfaa9571442a5fee5     casey   example37.jpg    on_task   
2    5fb7274529630080345884eb     casey  example183.jpg    on_task   
3    5fb7274dfaa9571442a5fee6     casey   example22.jpg    on_task   
4    5fb72758faa9571442a5fee7     casey   example86.jpg    on_task   
..                        ...       ...             ...        ...   
196                       NaN       NaN  example108.jpg        NaN   
197                       NaN       NaN  example117.jpg        NaN   
198                       NaN       NaN   example68.jpg        NaN   
199                       NaN       NaN  example169.jpg        NaN   
200                       NaN       NaN  example132.jpg        NaN   

                 emotion_x                     _id_y  user_id_y behavior_y  \
0    cant_decide_emotional  5fb8413951736e2ea19cfdf8  alexandra   off_task   
1    cant_decide_emotional  5fb8410676b1880504ea6e46  alexandra    on_task   
2                satisfied  5fb841ce51736e2ea19cfe01  alexandra    on_task   
3                satisfied  5fb83dc276b1880504ea6e13  alexandra    on_task   
4                satisfied  5fb8405a51736e2ea19cfde7  alexandra   off_task   
..                     ...                       ...        ...        ...   
196                    NaN  5fb842e651736e2ea19cfe10  alexandra    on_task   
197                    NaN  5fb8430651736e2ea19cfe12  alexandra    on_task   
198                    NaN  5fb8430e51736e2ea19cfe13  alexandra    on_task   
199                    NaN  5fb8432376b1880504ea6e5d  alexandra    on_task   
200                    NaN  5fb8437951736e2ea19cfe1a  alexandra    on_task   

     emotion_y  
0        bored  
1        bored  
2    satisfied  
3     confused  
4     confused  
..         ...  
196  satisfied  
197  satisfied  
198  satisfied  
199  satisfied  
200  satisfied  

[201 rows x 9 columns]

In [110]:
result[result.picture == "example140.jpg"]

_id_x user_id_x         picture behavior_x  \
0  5fb72727faa9571442a5fee4     casey  example140.jpg    on_task   

               emotion_x                     _id_y  user_id_y behavior_y  \
0  cant_decide_emotional  5fb8413951736e2ea19cfdf8  alexandra   off_task   

  emotion_y  
0     bored

In [112]:
# save to csv 
#df_alexandra.to_csv("alexandra_labeling.csv")
#df_casey.to_csv("casey_labeling.csv")
#result.to_csv("merged_labeling.csv")

### Model

In [2]:
import sys  
sys.path.insert(0, './code/') # we need this to import the vgg module
import VGG_model as vgg

In [5]:
# reload module after changes
imp.reload(vgg)

<module 'VGG_model' from './code/VGG_model.py'>

In [7]:
# this doesn't work for us
# er.dataset.load_from_save()

In [3]:
# load the model 
er = vgg.EmotionRecognition()
er.build_network()  # I modified this method to load the model already

[+] Building CNN
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Restoring parameters from /home/ubuntu/Engagement-Recognition/model/TF_final


In [9]:
# Just checking where this method came from - Bryan
print(er.model)
# help(er.model.retrieve_data_preprocessing_and_augmentation())

In [10]:
# Get the dimensions of the input using DNN class method
print(er.model.retrieve_data_preprocessing_and_augmentation())

({<tf.Tensor 'InputData/X:0' shape=(?, 48, 48, 1) dtype=float32>: <tflearn.data_augmentation.ImageAugmentation object at 0x7f6bbedc00b8>}, {<tf.Tensor 'InputData/X:0' shape=(?, 48, 48, 1) dtype=float32>: <tflearn.data_preprocessing.ImagePreprocessing object at 0x7f6bbedc0198>})


In [6]:
# get the names of the model layers
tflearn.variables.get_all_variables()

[<tf.Variable 'is_training:0' shape=() dtype=bool_ref>,
 <tf.Variable 'DataPreprocessing/mean:0' shape=<unknown> dtype=float32_ref>,
 <tf.Variable 'DataPreprocessing/mean_r:0' shape=() dtype=bool_ref>,
 <tf.Variable 'DataPreprocessing/std:0' shape=<unknown> dtype=float32_ref>,
 <tf.Variable 'DataPreprocessing/std_r:0' shape=() dtype=bool_ref>,
 <tf.Variable 'DataPreprocessing/pc:0' shape=<unknown> dtype=float32_ref>,
 <tf.Variable 'DataPreprocessing/pc_r:0' shape=() dtype=bool_ref>,
 <tf.Variable 'Conv2D/W:0' shape=(3, 3, 1, 64) dtype=float32_ref>,
 <tf.Variable 'Conv2D/b:0' shape=(64,) dtype=float32_ref>,
 <tf.Variable 'Conv2D_1/W:0' shape=(3, 3, 64, 64) dtype=float32_ref>,
 <tf.Variable 'Conv2D_1/b:0' shape=(64,) dtype=float32_ref>,
 <tf.Variable 'Conv2D_2/W:0' shape=(3, 3, 64, 128) dtype=float32_ref>,
 <tf.Variable 'Conv2D_2/b:0' shape=(128,) dtype=float32_ref>,
 <tf.Variable 'Conv2D_3/W:0' shape=(3, 3, 128, 128) dtype=float32_ref>,
 <tf.Variable 'Conv2D_3/b:0' shape=(128,) dtype=fl

In [13]:
# getting the weights of a specific layer
cnn_5_w = tflearn.get_layer_variables_by_name('Conv2D_5')[0]
er.model.get_weights(cnn_5_w)

array([[[[-3.20007056e-02, -6.63378695e-03,  3.35119478e-02, ...,
          -1.89169403e-03,  2.75813672e-03, -1.86928622e-02],
         [-9.23511107e-03,  3.65502737e-03, -3.68786947e-04, ...,
           1.54296858e-02, -6.32817578e-03,  9.05648526e-03],
         [ 2.02142261e-02, -1.10238185e-02,  2.25044470e-02, ...,
           2.14130152e-02, -4.25203443e-02,  6.05910458e-03],
         ...,
         [ 8.65779724e-03,  4.60811332e-03,  1.82808768e-02, ...,
          -8.95625539e-03,  1.60087552e-02, -8.47321004e-03],
         [-1.18457945e-02, -2.45467126e-02,  1.41137536e-03, ...,
          -7.76142115e-03,  6.75839372e-03,  6.91277627e-03],
         [-7.94100668e-03,  1.85862910e-02, -3.58703882e-02, ...,
           5.86689170e-03,  1.38103710e-02,  1.67537224e-03]],

        [[-1.02518862e-02, -1.66526274e-03,  6.37410255e-03, ...,
           1.44710941e-02,  2.68509127e-02,  2.20879167e-02],
         [-7.00736046e-03, -2.75647622e-02,  1.21044097e-02, ...,
           1.38250627e

In [22]:
# single image example
filename = 'ballon_resized.png'
image_example = cv2.imread(filename, cv2.IMREAD_GRAYSCALE).astype(np.float32) / 255.0
print(image_example.shape)
# normalization
#image_example -= image_example.mean()
#image_example /= image_example.std()
image_example

(48, 48)


array([[0.6745098 , 0.64705884, 0.6392157 , ..., 0.54509807, 0.57254905,
        0.6039216 ],
       [0.7647059 , 0.7294118 , 0.6862745 , ..., 0.59607846, 0.62352943,
        0.627451  ],
       [0.85882354, 0.8156863 , 0.7490196 , ..., 0.654902  , 0.6745098 ,
        0.69411767],
       ...,
       [0.83137256, 0.8235294 , 0.8117647 , ..., 0.7764706 , 0.7764706 ,
        0.7882353 ],
       [0.78431374, 0.8117647 , 0.85882354, ..., 0.827451  , 0.827451  ,
        0.76862746],
       [0.8156863 , 0.81960785, 0.8235294 , ..., 0.7882353 , 0.7882353 ,
        0.7882353 ]], dtype=float32)

In [19]:
data = np.array([image_example])
data = data.astype('float32')
data

array([[[0.6745098 , 0.64705884, 0.6392157 , ..., 0.54509807,
         0.57254905, 0.6039216 ],
        [0.7647059 , 0.7294118 , 0.6862745 , ..., 0.59607846,
         0.62352943, 0.627451  ],
        [0.85882354, 0.8156863 , 0.7490196 , ..., 0.654902  ,
         0.6745098 , 0.69411767],
        ...,
        [0.83137256, 0.8235294 , 0.8117647 , ..., 0.7764706 ,
         0.7764706 , 0.7882353 ],
        [0.78431374, 0.8117647 , 0.85882354, ..., 0.827451  ,
         0.827451  , 0.76862746],
        [0.8156863 , 0.81960785, 0.8235294 , ..., 0.7882353 ,
         0.7882353 , 0.7882353 ]]], dtype=float32)

In [20]:
er.predict(data)

(1, 48, 48)
(1, 48, 48, 1)


array([[0.05793414, 0.94206583]], dtype=float32)

In [179]:
p = "/path/im.jpg"
p.split(".")[-1]

'jpg'

### Dataset Preparation and Image Processing

In [4]:
def load_and_process_dataset(path = './dataset/',save_path = './resized_dataset/'):
    stream = os.listdir(path)
    dataset = []
    names = []
    for file in stream:
        # TODO: add support for other formats if needed
        if file.split(".")[-1] in {'jpg', 'png'}:
            img = crop_and_resize_image(file, path, save_path)
            sample = np.array( img, dtype=np.float32) 
            # normalization, from the paper: "For all the models, every sample of the ER dataset is 
            # normalized so that it has a zero mean and a norm equal to 100.0
            # sample -= sample.mean()
            # sample = sample / 100
            print(sample)
            dataset.append(sample)
            names.append(file)
    df = pd.DataFrame({'data_sample': dataset,  'name': names})
    return df

In [5]:
def crop_and_resize_image(name, path = './dataset/',save_path = './resized_dataset/', left = 0, top = 0, 
                          right = 1, bottom = 1, resize_h = 48, resize_w = 48, format_ = 'PNG', verbose = True):
    # Size of the image in pixels (size of orginal image) 
    item = path + name
    if verbose:
        print("Processing item:", item)
    im = Image.open(item).convert('L')
    width, height = im.size 
    # Setting the points for cropped image 
    left_ = left * width
    top_ = top * height
    right_ =  right * width
    bottom_ = bottom * height

    # Cropped image of above dimension 
    # (It will not change orginal image) 
    im1 = im.crop((left_, top_, right_, bottom_)) 

    im1 = im1.resize((resize_h,resize_w), Image.ANTIALIAS)
    im1.save(save_path + name.split(".")[0] + '_resized.png', format_, quality=90)
    
    return im1

In [6]:
data = load_and_process_dataset()
data.shape
data

Processing item: ./dataset/example82.jpg
[[-1.0188541 -1.0188541 -1.0188541 ... -1.0188541 -1.0188541 -1.0188541]
 [-1.0188541 -1.0188541 -1.0188541 ... -1.0188541 -1.0188541 -1.0188541]
 [-1.0188541 -1.0188541 -1.0188541 ... -1.0188541 -1.0188541 -1.0188541]
 ...
 [-1.0188541 -1.0188541 -1.0188541 ... -1.0188541 -1.0188541 -1.0188541]
 [-1.0188541 -1.0188541 -1.0188541 ... -1.0188541 -1.0188541 -1.0188541]
 [-1.0188541 -1.0188541 -1.0188541 ... -1.0188541 -1.0188541 -1.0188541]]
Processing item: ./dataset/example0.jpg
[[ 1.0665321   1.0565321   1.0565321  ...  0.99653214  0.99653214
   1.0065322 ]
 [ 1.0565321   1.0765321   0.9065321  ...  0.99653214  0.99653214
   1.0065322 ]
 [ 1.0465322   1.0765321   0.5165321  ...  0.99653214  0.99653214
   1.0065322 ]
 ...
 [-1.4734678  -1.4734678  -1.4734678  ...  0.9065321   0.94653213
   0.94653213]
 [-1.4734678  -1.4734678  -1.4734678  ...  0.92653215  0.92653215
   0.92653215]
 [-1.4734678  -1.4734678  -1.4734678  ...  0.8865321   0.87653214

data_sample            name
0    [[-1.0188541, -1.0188541, -1.0188541, -0.99885...   example82.jpg
1    [[1.0665321, 1.0565321, 1.0565321, 0.40653214,...    example0.jpg
2    [[0.10676651, 0.07676651, 0.14676651, 0.106766...   example31.jpg
3    [[-0.54498696, -0.09498695, 0.39501303, 0.3850...  example119.jpg
4    [[0.5162326, 0.4862326, 0.4862326, 0.4862326, ...   example96.jpg
..                                                 ...             ...
125  [[-0.53310335, -0.53310335, -0.52310336, -0.41...   example84.jpg
126  [[0.11137146, 0.18137147, 0.19137146, 0.171371...   example21.jpg
127  [[1.0551605, 1.0451605, 1.0451605, 0.59516054,...   example74.jpg
128  [[0.5263151, 0.4963151, 0.48631507, 0.48631507...   example30.jpg
129  [[0.12161453, 0.18161453, 0.17161453, 0.181614...   example54.jpg

[130 rows x 2 columns]

In [7]:
er.predict(np.array([data.data_sample]))

(1, 130, 48, 48)
(130, 48, 48, 1)


array([[0.0154681 , 0.98453194],
       [0.05423604, 0.945764  ],
       [0.09059794, 0.9094021 ],
       [0.06829229, 0.93170774],
       [0.23237339, 0.76762664],
       [0.10891365, 0.8910864 ],
       [0.02028362, 0.9797164 ],
       [0.23086746, 0.7691326 ],
       [0.02028583, 0.9797142 ],
       [0.06390815, 0.93609184],
       [0.0625529 , 0.9374472 ],
       [0.02595839, 0.97404164],
       [0.06287906, 0.9371209 ],
       [0.02008736, 0.97991264],
       [0.23027147, 0.76972854],
       [0.01954387, 0.9804561 ],
       [0.06211904, 0.937881  ],
       [0.10808966, 0.8919103 ],
       [0.02628795, 0.973712  ],
       [0.06255844, 0.9374416 ],
       [0.02620905, 0.97379094],
       [0.06601616, 0.9339839 ],
       [0.02568253, 0.97431743],
       [0.02539556, 0.97460437],
       [0.03596501, 0.964035  ],
       [0.02715948, 0.9728405 ],
       [0.05418152, 0.9458185 ],
       [0.22700027, 0.7729997 ],
       [0.02573306, 0.97426695],
       [0.01488761, 0.98511237],
       [0.

In [151]:
## testing their disengaged images

In [6]:
data = load_and_process_dataset(path = './mini_dataset/', save_path = './mini_dataset_resized/')
data.shape
data

Processing item: ./mini_dataset/disengaged2.png
[[ 76.  56.  62. ...  61. 102. 112.]
 [ 96.  92.  96. ...  48.  65.  80.]
 [ 94.  96. 105. ...  41.  44.  48.]
 ...
 [245. 245. 241. ... 127. 129. 130.]
 [246. 243. 245. ... 123. 126. 132.]
 [244. 245. 240. ... 126. 128. 132.]]
Processing item: ./mini_dataset/disengaged.png
[[146. 145. 146. ... 142. 141. 140.]
 [167. 165. 164. ... 147. 146. 144.]
 [188. 187. 187. ... 174. 171. 169.]
 ...
 [ 32.  24.  30. ...  53.  58.  67.]
 [ 31.  27.  31. ...  38.  40.  98.]
 [ 34.  30.  27. ...  34. 102. 189.]]
Processing item: ./mini_dataset/disengaged3.png
[[137. 136. 137. ... 147. 146. 145.]
 [141. 140. 140. ... 150. 150. 149.]
 [143. 144. 145. ... 152. 153. 154.]
 ...
 [109. 117.  85. ...   9.   9.   9.]
 [ 53.  55.  41. ...   9.   9.   8.]
 [ 44.  44.  47. ...   9.   9.   8.]]


data_sample             name
0  [[76.0, 56.0, 62.0, 86.0, 92.0, 100.0, 105.0, ...  disengaged2.png
1  [[146.0, 145.0, 146.0, 147.0, 147.0, 146.0, 14...   disengaged.png
2  [[137.0, 136.0, 137.0, 137.0, 138.0, 138.0, 13...  disengaged3.png

In [7]:
er.predict(np.array([data.data_sample]))

array([[1.05168415e-14, 1.00000000e+00],
       [1.68280962e-17, 1.00000000e+00],
       [1.98296317e-32, 1.00000000e+00]], dtype=float32)